#!/usr/bin/env python3
"""Render or verify the deterministic vendored loop-schema bundle.

The output is intentionally self-contained and uses only the Python standard
library. Consumers can pin the generated bundle to an exact source version and
commit without importing this repository at runtime.
"""

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

SOURCE_REPOSITORY = "brunovicco/engineering-loop-schemas"
MANIFEST_VERSION = "1.0.0"
SOURCE_FILES = ("models.py", "validate_contract.py")
COMMIT_PATTERN = re.compile(r"^[0-9a-f]{40}$")
SEMVER_PATTERN = re.compile(r"^\d+\.\d+\.\d+$")


def sha256_bytes(content: bytes) -> str:
    """Return a lowercase SHA-256 digest."""
    return hashlib.sha256(content).hexdigest()


def project_version(root: Path) -> str:
    """Read the package version from pyproject.toml."""
    with (root / "pyproject.toml").open("rb") as handle:
        document = tomllib.load(handle)
    project = document.get("project")
    if not isinstance(project, dict):
        raise ValueError("pyproject.toml has no [project] table")
    version = project.get("version")
    if not isinstance(version, str) or not SEMVER_PATTERN.fullmatch(version):
        raise ValueError(f"project.version must be semver, got {version!r}")
    return version


def git_commit(root: Path) -> str:
    """Resolve the exact source commit from the local checkout."""
    git = shutil.which("git")
    if git is None:
        raise ValueError("git executable was not found on PATH")
    result = subprocess.run(  # noqa: S603
        [git, "rev-parse", "HEAD"],
        cwd=root,
        check=False,
        capture_output=True,
        text=True,
    )
    commit = result.stdout.strip()
    if result.returncode or not COMMIT_PATTERN.fullmatch(commit):
        raise ValueError("could not resolve a full Git commit; pass --source-commit explicitly")
    return commit


def vendor_header(version: str, commit: str) -> str:
    """Return the common deterministic provenance header."""
    return (
        "# Vendored from brunovicco/engineering-loop-schemas\n"
        f"# Version: {version}\n"
        f"# Commit: {commit}\n"
        "# Generated by scripts/render_vendor_bundle.py; do not edit by hand.\n"
        "# Phase 0-1 remains report-only: this bundle validates contracts only.\n"
    )


def render_models(source: str, version: str, commit: str) -> str:
    """Render models.py with a deterministic provenance header."""
    return f"{vendor_header(version, commit)}{source}"


def render_validator(source: str, version: str, commit: str) -> str:
    """Render validate_contract.py and adapt its package import."""
    shebang = ""
    body = source
    if body.startswith("#!"):
        shebang, body = body.split("\n", 1)
        shebang += "\n"

    original = "from loop_schemas.models import Contract"
    adapted = "from _vendor_loop_schemas.models import Contract"
    if original not in body:
        raise ValueError(f"expected import not found: {original}")
    body = body.replace(original, adapted, 1)
    if original in body:
        raise ValueError("unexpected second source-package import remains")
    return f"{shebang}{vendor_header(version, commit)}{body}"


def render_init(version: str, commit: str) -> str:
    """Render the vendored package marker."""
    return (
        f"{vendor_header(version, commit)}"
        '"""Vendored validators for Evidence-Gated Engineering Loop contracts."""\n'
    )


def expected_files(
    source_root: Path,
    *,
    version: str,
    commit: str,
    repository: str,
) -> dict[str, bytes]:
    """Build the complete deterministic bundle in memory."""
    source_dir = source_root / "src" / "loop_schemas"
    models = (source_dir / "models.py").read_text(encoding="utf-8")
    validator = (source_dir / "validate_contract.py").read_text(encoding="utf-8")

    rendered: dict[str, bytes] = {
        "__init__.py": render_init(version, commit).encode(),
        "models.py": render_models(models, version, commit).encode(),
        "validate_contract.py": render_validator(validator, version, commit).encode(),
    }
    manifest = {
        "manifest_version": MANIFEST_VERSION,
        "source": {
            "repository": repository,
            "version": version,
            "commit": commit,
        },
        "adaptations": [
            {
                "file": "validate_contract.py",
                "from": "from loop_schemas.models import Contract",
                "to": "from _vendor_loop_schemas.models import Contract",
            }
        ],
        "files": {
            name: {"sha256": sha256_bytes(content), "size_bytes": len(content)}
            for name, content in sorted(rendered.items())
        },
    }
    rendered["manifest.json"] = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode()
    return rendered


def compare_bundle(target: Path, expected: dict[str, bytes]) -> list[str]:
    """Return deterministic drift errors for an existing target."""
    errors: list[str] = []
    expected_names = set(expected)
    existing_names = {path.name for path in target.iterdir()} if target.exists() else set()

    for missing in sorted(expected_names - existing_names):
        errors.append(f"missing vendored file: {missing}")
    for unexpected in sorted(existing_names - expected_names):
        errors.append(f"unexpected vendored file: {unexpected}")

    for name, expected_content in sorted(expected.items()):
        path = target / name
        if not path.is_file():
            continue
        actual_content = path.read_bytes()
        if actual_content != expected_content:
            errors.append(
                f"drift detected in {name}: expected "
                f"{sha256_bytes(expected_content)}, got {sha256_bytes(actual_content)}"
            )
    return errors


def write_bundle(target: Path, expected: dict[str, bytes]) -> None:
    """Write the bundle atomically per file."""
    target.mkdir(parents=True, exist_ok=True)
    expected_names = set(expected)
    for path in target.iterdir():
        if path.is_file() and path.name not in expected_names:
            path.unlink()
    for name, content in sorted(expected.items()):
        destination = target / name
        temporary = destination.with_suffix(destination.suffix + ".tmp")
        temporary.write_bytes(content)
        temporary.replace(destination)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", type=Path, required=True)
    parser.add_argument("--source-root", type=Path)
    parser.add_argument("--source-version")
    parser.add_argument("--source-commit")
    parser.add_argument("--source-repository", default=SOURCE_REPOSITORY)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Render or verify a bundle."""
    args = parse_args(argv)
    source_root = (args.source_root or Path(__file__).resolve().parents[1]).resolve()
    version = args.source_version or project_version(source_root)
    commit = args.source_commit or git_commit(source_root)

    if not SEMVER_PATTERN.fullmatch(version):
        print(f"invalid source version: {version!r}", file=sys.stderr)
        return 2
    if not COMMIT_PATTERN.fullmatch(commit):
        print(f"invalid full source commit: {commit!r}", file=sys.stderr)
        return 2

    expected = expected_files(
        source_root,
        version=version,
        commit=commit,
        repository=args.source_repository,
    )
    target = args.target.resolve()

    if args.check:
        errors = compare_bundle(target, expected)
        if errors:
            print("Vendored loop-schema bundle is out of date:", file=sys.stderr)
            for error in errors:
                print(f"- {error}", file=sys.stderr)
            return 1
        print(
            f"Vendored loop-schema bundle matches {version} @ {commit}.",
            flush=True,
        )
        return 0

    write_bundle(target, expected)
    print(f"Rendered {target} from {version} @ {commit}.", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
