#!/usr/bin/env python3
"""Render or verify the deterministic vendored loop-schema bundle.

The output is intentionally self-contained and uses only the Python standard
library. Consumers can pin the generated bundle to an exact source version and
commit without importing this repository at runtime.
"""

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

SOURCE_REPOSITORY = "brunovicco/engineering-loop-schemas"
MANIFEST_VERSION = "2.0.0"
SOURCE_FILES = (
    "_stdlib_jsonschema.py",
    "models.py",
    "schema_resources.py",
    "validate_contract.py",
)
SCHEMA_FILES = (
    "builder-result.schema.json",
    "contract.schema.json",
    "evidence.schema.json",
    "verdict.schema.json",
)
COMMIT_PATTERN = re.compile(r"^[0-9a-f]{40}$")
SEMVER_PATTERN = re.compile(r"^\d+\.\d+\.\d+$")


def sha256_bytes(content: bytes) -> str:
    """Return a lowercase SHA-256 digest."""
    return hashlib.sha256(content).hexdigest()


def project_version(root: Path) -> str:
    """Read the package version from pyproject.toml."""
    with (root / "pyproject.toml").open("rb") as handle:
        document = tomllib.load(handle)
    project = document.get("project")
    if not isinstance(project, dict):
        raise ValueError("pyproject.toml has no [project] table")
    version = project.get("version")
    if not isinstance(version, str) or not SEMVER_PATTERN.fullmatch(version):
        raise ValueError(f"project.version must be semver, got {version!r}")
    return version


def run_git(root: Path, *arguments: str) -> str:
    """Run one read-only Git command and return stripped stdout."""
    git = shutil.which("git")
    if git is None:
        raise ValueError("git executable was not found on PATH")
    result = subprocess.run(  # noqa: S603
        [git, *arguments],
        cwd=root,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode:
        detail = result.stderr.strip() or "Git command failed"
        raise ValueError(detail)
    return result.stdout.strip()


def git_commit(root: Path) -> str:
    """Resolve the exact source commit from the local checkout."""
    commit = run_git(root, "rev-parse", "HEAD")
    if not COMMIT_PATTERN.fullmatch(commit):
        raise ValueError("could not resolve a full Git commit")
    return commit


def normalize_repository(value: str) -> str:
    """Normalize a GitHub origin URL to ``owner/repository``."""
    normalized = value.strip()
    prefixes = (
        "https://github.com/",
        "http://github.com/",
        "ssh://git@github.com/",
        "git://github.com/",
        "git@github.com:",
    )
    for prefix in prefixes:
        if normalized.startswith(prefix):
            normalized = normalized.removeprefix(prefix)
            break
    else:
        raise ValueError(f"unsupported source repository URL: {value!r}")
    return normalized.removesuffix(".git").strip("/")


def verify_source_identity(
    root: Path,
    *,
    version: str,
    commit: str,
    repository: str,
) -> None:
    """Bind declared provenance to a clean local Git checkout."""
    actual_version = project_version(root)
    if version != actual_version:
        raise ValueError(
            f"declared source version {version!r} does not match project version {actual_version!r}"
        )

    actual_commit = git_commit(root)
    if commit != actual_commit:
        raise ValueError(f"declared source commit {commit!r} does not match HEAD {actual_commit!r}")

    actual_repository = normalize_repository(run_git(root, "config", "--get", "remote.origin.url"))
    if repository != actual_repository:
        raise ValueError(
            f"declared source repository {repository!r} does not match origin {actual_repository!r}"
        )

    dirty = run_git(root, "status", "--porcelain=v1", "--untracked-files=all")
    if dirty:
        raise ValueError("source working tree is not clean")


def vendor_header(version: str, commit: str) -> str:
    """Return the common deterministic provenance header."""
    return (
        "# Vendored from brunovicco/engineering-loop-schemas\n"
        f"# Version: {version}\n"
        f"# Commit: {commit}\n"
        "# Generated by scripts/render_vendor_bundle.py; do not edit by hand.\n"
        "# Report-only boundary: this bundle validates schema documents only.\n"
    )


def render_source(source: str, version: str, commit: str) -> str:
    """Render an ordinary Python source with a provenance header."""
    return f"{vendor_header(version, commit)}{source}"


def render_validator(source: str, version: str, commit: str) -> str:
    """Render validate_contract.py and adapt its package import."""
    shebang = ""
    body = source
    if body.startswith("#!"):
        shebang, body = body.split("\n", 1)
        shebang += "\n"

    adaptations = (
        (
            "from loop_schemas._stdlib_jsonschema import",
            "from _vendor_loop_schemas._stdlib_jsonschema import",
        ),
        (
            "from loop_schemas.models import Contract",
            "from _vendor_loop_schemas.models import Contract",
        ),
        (
            "from loop_schemas.schema_resources import",
            "from _vendor_loop_schemas.schema_resources import",
        ),
    )
    for original, adapted in adaptations:
        if original not in body:
            raise ValueError(f"expected import not found: {original}")
        body = body.replace(original, adapted, 1)
        if original in body:
            raise ValueError(f"unexpected second source-package import remains: {original}")
    return f"{shebang}{vendor_header(version, commit)}{body}"


def render_init(version: str, commit: str) -> str:
    """Render the vendored package marker."""
    return (
        f"{vendor_header(version, commit)}"
        '"""Vendored validators for Evidence-Gated Engineering Loop documents."""\n'
    )


def expected_files(
    source_root: Path,
    *,
    version: str,
    commit: str,
    repository: str,
) -> dict[str, bytes]:
    """Build the complete deterministic bundle in memory."""
    source_dir = source_root / "src" / "loop_schemas"
    rendered: dict[str, bytes] = {"__init__.py": render_init(version, commit).encode()}
    for name in SOURCE_FILES:
        source = (source_dir / name).read_text(encoding="utf-8")
        content = (
            render_validator(source, version, commit)
            if name == "validate_contract.py"
            else render_source(source, version, commit)
        )
        rendered[name] = content.encode()
    for name in SCHEMA_FILES:
        rendered[f"schemas/{name}"] = (source_root / "schemas" / name).read_bytes()

    adaptations = (
        (
            "from loop_schemas._stdlib_jsonschema import",
            "from _vendor_loop_schemas._stdlib_jsonschema import",
        ),
        (
            "from loop_schemas.models import Contract",
            "from _vendor_loop_schemas.models import Contract",
        ),
        (
            "from loop_schemas.schema_resources import",
            "from _vendor_loop_schemas.schema_resources import",
        ),
    )
    manifest = {
        "manifest_version": MANIFEST_VERSION,
        "source": {
            "repository": repository,
            "version": version,
            "commit": commit,
        },
        "adaptations": [
            {"file": "validate_contract.py", "from": original, "to": adapted}
            for original, adapted in adaptations
        ],
        "files": {
            name: {"sha256": sha256_bytes(content), "size_bytes": len(content)}
            for name, content in sorted(rendered.items())
        },
    }
    rendered["manifest.json"] = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode()
    return rendered


def compare_bundle(target: Path, expected: dict[str, bytes]) -> list[str]:
    """Return deterministic drift errors for an existing target."""
    errors: list[str] = []
    expected_names = set(expected)
    existing_names = (
        {
            path.relative_to(target).as_posix()
            for path in target.rglob("*")
            if path.is_file() or path.is_symlink()
        }
        if target.exists() and target.is_dir()
        else set()
    )

    for missing in sorted(expected_names - existing_names):
        errors.append(f"missing vendored file: {missing}")
    for unexpected in sorted(existing_names - expected_names):
        errors.append(f"unexpected vendored file: {unexpected}")

    for name, expected_content in sorted(expected.items()):
        path = target / name
        if path.is_symlink():
            errors.append(f"vendored file must not be a symbolic link: {name}")
            continue
        if not path.is_file():
            continue
        actual_content = path.read_bytes()
        if actual_content != expected_content:
            errors.append(
                f"drift detected in {name}: expected "
                f"{sha256_bytes(expected_content)}, got {sha256_bytes(actual_content)}"
            )
    return errors


def write_bundle(target: Path, expected: dict[str, bytes]) -> None:
    """Stage the complete bundle and replace the target as one transaction."""
    if target.exists() and not target.is_dir():
        raise ValueError(f"bundle target is not a directory: {target}")
    target.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=f".{target.name}.staging-", dir=target.parent))
    backup: Path | None = None
    try:
        for name, content in sorted(expected.items()):
            destination = staging / name
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(content)

        if target.exists():
            backup = Path(tempfile.mkdtemp(prefix=f".{target.name}.backup-", dir=target.parent))
            backup.rmdir()
            target.replace(backup)
        try:
            staging.replace(target)
        except OSError:
            if backup is not None:
                backup.replace(target)
            raise
        if backup is not None:
            shutil.rmtree(backup)
    finally:
        if staging.exists():
            shutil.rmtree(staging)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", type=Path, required=True)
    parser.add_argument("--source-root", type=Path)
    parser.add_argument("--source-version")
    parser.add_argument("--source-commit")
    parser.add_argument("--source-repository", default=SOURCE_REPOSITORY)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Render or verify a bundle."""
    args = parse_args(argv)
    source_root = (args.source_root or Path(__file__).resolve().parents[1]).resolve()
    try:
        version = args.source_version or project_version(source_root)
        commit = args.source_commit or git_commit(source_root)
        if not SEMVER_PATTERN.fullmatch(version):
            raise ValueError(f"invalid source version: {version!r}")
        if not COMMIT_PATTERN.fullmatch(commit):
            raise ValueError(f"invalid full source commit: {commit!r}")
        verify_source_identity(
            source_root,
            version=version,
            commit=commit,
            repository=args.source_repository,
        )
    except ValueError as exc:
        print(f"invalid source provenance: {exc}", file=sys.stderr)
        return 2

    expected = expected_files(
        source_root,
        version=version,
        commit=commit,
        repository=args.source_repository,
    )
    target = args.target.resolve()

    if args.check:
        errors = compare_bundle(target, expected)
        if errors:
            print("Vendored loop-schema bundle is out of date:", file=sys.stderr)
            for error in errors:
                print(f"- {error}", file=sys.stderr)
            return 1
        print(
            f"Vendored loop-schema bundle matches {version} @ {commit}.",
            flush=True,
        )
        return 0

    write_bundle(target, expected)
    print(f"Rendered {target} from {version} @ {commit}.", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
